-- MySQL Script generated by MySQL Workbench
-- mar. 18 janv. 2022 15:43:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(125) NOT NULL,
  `lastname` VARCHAR(125) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `validate` TINYINT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `image` VARCHAR(125) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Teacher_user`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`level` ;

CREATE TABLE IF NOT EXISTS `mydb`.`level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `logo` VARCHAR(125) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lesson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lesson` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `level_id` INT NULL,
  `logo` VARCHAR(125) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_level_idx` (`level_id` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_level`
    FOREIGN KEY (`level_id`)
    REFERENCES `mydb`.`level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teacher_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_offer_teacher_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `fk_offer_lesson_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_offer_teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_lesson`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`assist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`assist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `offer_id` INT NOT NULL,
  `meet` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assist_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_assist_offer_idx` (`offer_id` ASC) VISIBLE,
  CONSTRAINT `fk_assist_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assist_offer`
    FOREIGN KEY (`offer_id`)
    REFERENCES `mydb`.`offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`message` ;

CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(125) NOT NULL,
  `message` VARCHAR(45) NULL,
  `message_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
